export const GET_GAME_DATA_REQUEST = 'GET_GAME_DATA_REQUEST';
export const GET_GAME_DATA = 'GET_GAME_DATA';

export const UPDATE_GAME_DATA = 'UPDATE_GAME_DATA';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const UPDATE_PLAYER_SETTINGS = 'UPDATE_PLAYER_SETTINGS';

export const RESET_GAME_STATUS = 'RESET_GAME_STATUS';
